package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8944167746240261058L;
	private String carCod;
     private String carDes;

    public Cargo() {
    }

    public Cargo(String carCod, String carDes) {
       this.carCod = carCod;
       this.carDes = carDes;
    }
   
    public String getCarCod() {
        return this.carCod;
    }
    
    public void setCarCod(String carCod) {
        this.carCod = carCod;
    }
    public String getCarDes() {
        return this.carDes;
    }
    
    public void setCarDes(String carDes) {
        this.carDes = carDes;
    }




}


