package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Ciuda generated by hbm2java
 */
public class Ciuda  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CiudaId id;
     private String ciuNom;

    public Ciuda() {
    }

    public Ciuda(CiudaId id, String ciuNom) {
       this.id = id;
       this.ciuNom = ciuNom;
    }
   
    public CiudaId getId() {
        return this.id;
    }
    
    public void setId(CiudaId id) {
        this.id = id;
    }
    public String getCiuNom() {
        return this.ciuNom;
    }
    
    public void setCiuNom(String ciuNom) {
        this.ciuNom = ciuNom;
    }




}


