package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * CiudaId generated by hbm2java
 */
public class CiudaId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8803172714840265849L;
	private Long depCod;
     private Long ciuCod;

    public CiudaId() {
    }

    public CiudaId(Long depCod, Long ciuCod) {
       this.depCod = depCod;
       this.ciuCod = ciuCod;
    }
   
    public Long getDepCod() {
        return this.depCod;
    }
    
    public void setDepCod(Long depCod) {
        this.depCod = depCod;
    }
    public Long getCiuCod() {
        return this.ciuCod;
    }
    
    public void setCiuCod(Long ciuCod) {
        this.ciuCod = ciuCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CiudaId) ) return false;
		 CiudaId castOther = ( CiudaId ) other; 
         
		 return ( (this.getDepCod()==castOther.getDepCod()) || ( this.getDepCod()!=null && castOther.getDepCod()!=null && this.getDepCod().equals(castOther.getDepCod()) ) )
 && ( (this.getCiuCod()==castOther.getCiuCod()) || ( this.getCiuCod()!=null && castOther.getCiuCod()!=null && this.getCiuCod().equals(castOther.getCiuCod()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDepCod() == null ? 0 : this.getDepCod().hashCode() );
         result = 37 * result + ( getCiuCod() == null ? 0 : this.getCiuCod().hashCode() );
         return result;
   }   


}


