package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Contratos generated by hbm2java
 */
public class Contratos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -190245610668401071L;
	private ContratosId id;
     private Date conFec;
     private Long conVal;
     private Long conUsu;
     private Long conDura;
     private Date conFecFac;
     private Long conNroFac;
     private String socCod;
     private String conEst;
     private String conObser;
     private String conTipo;
     private Long detConCod;
     private Long conDosi;

    public Contratos() {
    }

	
    public Contratos(ContratosId id, Date conFec, Long conVal, Long conUsu, Long conDura, String socCod, String conEst, String conTipo) {
        this.id = id;
        this.conFec = conFec;
        this.conVal = conVal;
        this.conUsu = conUsu;
        this.conDura = conDura;
        this.socCod = socCod;
        this.conEst = conEst;
        this.conTipo = conTipo;
    }
    public Contratos(ContratosId id, Date conFec, Long conVal, Long conUsu, Long conDura, Date conFecFac, Long conNroFac, String socCod, String conEst, String conObser, String conTipo, Long detConCod, Long conDosi) {
       this.id = id;
       this.conFec = conFec;
       this.conVal = conVal;
       this.conUsu = conUsu;
       this.conDura = conDura;
       this.conFecFac = conFecFac;
       this.conNroFac = conNroFac;
       this.socCod = socCod;
       this.conEst = conEst;
       this.conObser = conObser;
       this.conTipo = conTipo;
       this.detConCod = detConCod;
       this.conDosi = conDosi;
    }
   
    public ContratosId getId() {
        return this.id;
    }
    
    public void setId(ContratosId id) {
        this.id = id;
    }
    public Date getConFec() {
        return this.conFec;
    }
    
    public void setConFec(Date conFec) {
        this.conFec = conFec;
    }
    public Long getConVal() {
        return this.conVal;
    }
    
    public void setConVal(Long conVal) {
        this.conVal = conVal;
    }
    public Long getConUsu() {
        return this.conUsu;
    }
    
    public void setConUsu(Long conUsu) {
        this.conUsu = conUsu;
    }
    public Long getConDura() {
        return this.conDura;
    }
    
    public void setConDura(Long conDura) {
        this.conDura = conDura;
    }
    public Date getConFecFac() {
        return this.conFecFac;
    }
    
    public void setConFecFac(Date conFecFac) {
        this.conFecFac = conFecFac;
    }
    public Long getConNroFac() {
        return this.conNroFac;
    }
    
    public void setConNroFac(Long conNroFac) {
        this.conNroFac = conNroFac;
    }
    public String getSocCod() {
        return this.socCod;
    }
    
    public void setSocCod(String socCod) {
        this.socCod = socCod;
    }
    public String getConEst() {
        return this.conEst;
    }
    
    public void setConEst(String conEst) {
        this.conEst = conEst;
    }
    public String getConObser() {
        return this.conObser;
    }
    
    public void setConObser(String conObser) {
        this.conObser = conObser;
    }
    public String getConTipo() {
        return this.conTipo;
    }
    
    public void setConTipo(String conTipo) {
        this.conTipo = conTipo;
    }
    public Long getDetConCod() {
        return this.detConCod;
    }
    
    public void setDetConCod(Long detConCod) {
        this.detConCod = detConCod;
    }
    public Long getConDosi() {
        return this.conDosi;
    }
    
    public void setConDosi(Long conDosi) {
        this.conDosi = conDosi;
    }




}


