package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * DetalleContrato generated by hbm2java
 */
public class DetalleContrato  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2274528191658968703L;
	private DetalleContratoId id;
     private Long detNumUsu;
     private String detObs;
     private String detEst;

    public DetalleContrato() {
    }

	
    public DetalleContrato(DetalleContratoId id, Long detNumUsu, String detEst) {
        this.id = id;
        this.detNumUsu = detNumUsu;
        this.detEst = detEst;
    }
    public DetalleContrato(DetalleContratoId id, Long detNumUsu, String detObs, String detEst) {
       this.id = id;
       this.detNumUsu = detNumUsu;
       this.detObs = detObs;
       this.detEst = detEst;
    }
   
    public DetalleContratoId getId() {
        return this.id;
    }
    
    public void setId(DetalleContratoId id) {
        this.id = id;
    }
    public Long getDetNumUsu() {
        return this.detNumUsu;
    }
    
    public void setDetNumUsu(Long detNumUsu) {
        this.detNumUsu = detNumUsu;
    }
    public String getDetObs() {
        return this.detObs;
    }
    
    public void setDetObs(String detObs) {
        this.detObs = detObs;
    }
    public String getDetEst() {
        return this.detEst;
    }
    
    public void setDetEst(String detEst) {
        this.detEst = detEst;
    }




}


