package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * DetalleContratoId generated by hbm2java
 */
public class DetalleContratoId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1191839707054443861L;
	private Long detConCod;
     private Long conNro;

    public DetalleContratoId() {
    }

    public DetalleContratoId(Long detConCod, Long conNro) {
       this.detConCod = detConCod;
       this.conNro = conNro;
    }
   
    public Long getDetConCod() {
        return this.detConCod;
    }
    
    public void setDetConCod(Long detConCod) {
        this.detConCod = detConCod;
    }
    public Long getConNro() {
        return this.conNro;
    }
    
    public void setConNro(Long conNro) {
        this.conNro = conNro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleContratoId) ) return false;
		 DetalleContratoId castOther = ( DetalleContratoId ) other; 
         
		 return ( (this.getDetConCod()==castOther.getDetConCod()) || ( this.getDetConCod()!=null && castOther.getDetConCod()!=null && this.getDetConCod().equals(castOther.getDetConCod()) ) )
 && ( (this.getConNro()==castOther.getConNro()) || ( this.getConNro()!=null && castOther.getConNro()!=null && this.getConNro().equals(castOther.getConNro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDetConCod() == null ? 0 : this.getDetConCod().hashCode() );
         result = 37 * result + ( getConNro() == null ? 0 : this.getConNro().hashCode() );
         return result;
   }   


}


