package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * DosimetroId generated by hbm2java
 */
public class DosimetroId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 9160820626337305925L;
	private Long traCed;
     private Long dosCod;
     private Long empCod;

    public DosimetroId() {
    }

    public DosimetroId(Long traCed, Long dosCod, Long empCod) {
       this.traCed = traCed;
       this.dosCod = dosCod;
       this.empCod = empCod;
    }
   
    public Long getTraCed() {
        return this.traCed;
    }
    
    public void setTraCed(Long traCed) {
        this.traCed = traCed;
    }
    public Long getDosCod() {
        return this.dosCod;
    }
    
    public void setDosCod(Long dosCod) {
        this.dosCod = dosCod;
    }
    public Long getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Long empCod) {
        this.empCod = empCod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DosimetroId) ) return false;
		 DosimetroId castOther = ( DosimetroId ) other; 
         
		 return ( (this.getTraCed()==castOther.getTraCed()) || ( this.getTraCed()!=null && castOther.getTraCed()!=null && this.getTraCed().equals(castOther.getTraCed()) ) )
 && ( (this.getDosCod()==castOther.getDosCod()) || ( this.getDosCod()!=null && castOther.getDosCod()!=null && this.getDosCod().equals(castOther.getDosCod()) ) )
 && ( (this.getEmpCod()==castOther.getEmpCod()) || ( this.getEmpCod()!=null && castOther.getEmpCod()!=null && this.getEmpCod().equals(castOther.getEmpCod()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTraCed() == null ? 0 : this.getTraCed().hashCode() );
         result = 37 * result + ( getDosCod() == null ? 0 : this.getDosCod().hashCode() );
         result = 37 * result + ( getEmpCod() == null ? 0 : this.getEmpCod().hashCode() );
         return result;
   }   


}


