package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Dosimetro generated by hbm2java
 */
public class Dosimetro  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6539444794636237292L;
	private DosimetroId id;
     private Long dosConNro;
     private String dosEst;
     private String praCod;
     private String radCod;
     private String geoCod;
     private String ubiCod;
     private String carCod;
     private Long dosPerRec;
     private String dosTipo;

    public Dosimetro() {
    }

    public Dosimetro(DosimetroId id, Long dosConNro, String dosEst, String praCod, String radCod, String geoCod, String ubiCod, String carCod, Long dosPerRec, String dosTipo) {
       this.id = id;
       this.dosConNro = dosConNro;
       this.dosEst = dosEst;
       this.praCod = praCod;
       this.radCod = radCod;
       this.geoCod = geoCod;
       this.ubiCod = ubiCod;
       this.carCod = carCod;
       this.dosPerRec = dosPerRec;
       this.dosTipo = dosTipo;
    }
   
    public DosimetroId getId() {
        return this.id;
    }
    
    public void setId(DosimetroId id) {
        this.id = id;
    }
    public Long getDosConNro() {
        return this.dosConNro;
    }
    
    public void setDosConNro(Long dosConNro) {
        this.dosConNro = dosConNro;
    }
    public String getDosEst() {
        return this.dosEst;
    }
    
    public void setDosEst(String dosEst) {
        this.dosEst = dosEst;
    }
    public String getPraCod() {
        return this.praCod;
    }
    
    public void setPraCod(String praCod) {
        this.praCod = praCod;
    }
    public String getRadCod() {
        return this.radCod;
    }
    
    public void setRadCod(String radCod) {
        this.radCod = radCod;
    }
    public String getGeoCod() {
        return this.geoCod;
    }
    
    public void setGeoCod(String geoCod) {
        this.geoCod = geoCod;
    }
    public String getUbiCod() {
        return this.ubiCod;
    }
    
    public void setUbiCod(String ubiCod) {
        this.ubiCod = ubiCod;
    }
    public String getCarCod() {
        return this.carCod;
    }
    
    public void setCarCod(String carCod) {
        this.carCod = carCod;
    }
    public Long getDosPerRec() {
        return this.dosPerRec;
    }
    
    public void setDosPerRec(Long dosPerRec) {
        this.dosPerRec = dosPerRec;
    }
    public String getDosTipo() {
        return this.dosTipo;
    }
    
    public void setDosTipo(String dosTipo) {
        this.dosTipo = dosTipo;
    }




}


