package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2643779779604450237L;
	private Long empCod;
     private Long empNit;
     private String empRazSoc;
     private String empDir;
     private String empTel;
     private String empFax;
     private String empCel;
     private Date empFecVin;
     private String empEst;
     private String empMail;
     private Long depCod;
     private String empObs;
     private Long ciuCod;
     private String empNomCon;
     private String empApe1con;
     private String empCarCon;
     private String empCel1;
     private String empConMail;
     private String empNomCom2;
     private String empApe1con2;
     private String empCarCon2;
     private String empCel2;
     private String empConMail2;

    public Empresas() {
    }

	
    public Empresas(Long empCod, Long empNit, Date empFecVin, String empEst, Long depCod, Long ciuCod) {
        this.empCod = empCod;
        this.empNit = empNit;
        this.empFecVin = empFecVin;
        this.empEst = empEst;
        this.depCod = depCod;
        this.ciuCod = ciuCod;
    }
    public Empresas(Long empCod, Long empNit, String empRazSoc, String empDir, String empTel, String empFax, String empCel, Date empFecVin, String empEst, String empMail, Long depCod, String empObs, Long ciuCod, String empNomCon, String empApe1con, String empCarCon, String empCel1, String empConMail, String empNomCom2, String empApe1con2, String empCarCon2, String empCel2, String empConMail2) {
       this.empCod = empCod;
       this.empNit = empNit;
       this.empRazSoc = empRazSoc;
       this.empDir = empDir;
       this.empTel = empTel;
       this.empFax = empFax;
       this.empCel = empCel;
       this.empFecVin = empFecVin;
       this.empEst = empEst;
       this.empMail = empMail;
       this.depCod = depCod;
       this.empObs = empObs;
       this.ciuCod = ciuCod;
       this.empNomCon = empNomCon;
       this.empApe1con = empApe1con;
       this.empCarCon = empCarCon;
       this.empCel1 = empCel1;
       this.empConMail = empConMail;
       this.empNomCom2 = empNomCom2;
       this.empApe1con2 = empApe1con2;
       this.empCarCon2 = empCarCon2;
       this.empCel2 = empCel2;
       this.empConMail2 = empConMail2;
    }
   
    public Long getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Long empCod) {
        this.empCod = empCod;
    }
    public Long getEmpNit() {
        return this.empNit;
    }
    
    public void setEmpNit(Long empNit) {
        this.empNit = empNit;
    }
    public String getEmpRazSoc() {
        return this.empRazSoc;
    }
    
    public void setEmpRazSoc(String empRazSoc) {
        this.empRazSoc = empRazSoc;
    }
    public String getEmpDir() {
        return this.empDir;
    }
    
    public void setEmpDir(String empDir) {
        this.empDir = empDir;
    }
    public String getEmpTel() {
        return this.empTel;
    }
    
    public void setEmpTel(String empTel) {
        this.empTel = empTel;
    }
    public String getEmpFax() {
        return this.empFax;
    }
    
    public void setEmpFax(String empFax) {
        this.empFax = empFax;
    }
    public String getEmpCel() {
        return this.empCel;
    }
    
    public void setEmpCel(String empCel) {
        this.empCel = empCel;
    }
    public Date getEmpFecVin() {
        return this.empFecVin;
    }
    
    public void setEmpFecVin(Date empFecVin) {
        this.empFecVin = empFecVin;
    }
    public String getEmpEst() {
        return this.empEst;
    }
    
    public void setEmpEst(String empEst) {
        this.empEst = empEst;
    }
    public String getEmpMail() {
        return this.empMail;
    }
    
    public void setEmpMail(String empMail) {
        this.empMail = empMail;
    }
    public Long getDepCod() {
        return this.depCod;
    }
    
    public void setDepCod(Long depCod) {
        this.depCod = depCod;
    }
    public String getEmpObs() {
        return this.empObs;
    }
    
    public void setEmpObs(String empObs) {
        this.empObs = empObs;
    }
    public Long getCiuCod() {
        return this.ciuCod;
    }
    
    public void setCiuCod(Long ciuCod) {
        this.ciuCod = ciuCod;
    }
    public String getEmpNomCon() {
        return this.empNomCon;
    }
    
    public void setEmpNomCon(String empNomCon) {
        this.empNomCon = empNomCon;
    }
    public String getEmpApe1con() {
        return this.empApe1con;
    }
    
    public void setEmpApe1con(String empApe1con) {
        this.empApe1con = empApe1con;
    }
    public String getEmpCarCon() {
        return this.empCarCon;
    }
    
    public void setEmpCarCon(String empCarCon) {
        this.empCarCon = empCarCon;
    }
    public String getEmpCel1() {
        return this.empCel1;
    }
    
    public void setEmpCel1(String empCel1) {
        this.empCel1 = empCel1;
    }
    public String getEmpConMail() {
        return this.empConMail;
    }
    
    public void setEmpConMail(String empConMail) {
        this.empConMail = empConMail;
    }
    public String getEmpNomCom2() {
        return this.empNomCom2;
    }
    
    public void setEmpNomCom2(String empNomCom2) {
        this.empNomCom2 = empNomCom2;
    }
    public String getEmpApe1con2() {
        return this.empApe1con2;
    }
    
    public void setEmpApe1con2(String empApe1con2) {
        this.empApe1con2 = empApe1con2;
    }
    public String getEmpCarCon2() {
        return this.empCarCon2;
    }
    
    public void setEmpCarCon2(String empCarCon2) {
        this.empCarCon2 = empCarCon2;
    }
    public String getEmpCel2() {
        return this.empCel2;
    }
    
    public void setEmpCel2(String empCel2) {
        this.empCel2 = empCel2;
    }
    public String getEmpConMail2() {
        return this.empConMail2;
    }
    
    public void setEmpConMail2(String empConMail2) {
        this.empConMail2 = empConMail2;
    }




}


