package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Facturapago generated by hbm2java
 */
public class Facturapago  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7512622052544707815L;
	private FacturapagoId id;
     private Date facPagFec;
     private Double facPagVal;
     private Double facPagRet;

    public Facturapago() {
    }

    public Facturapago(FacturapagoId id, Date facPagFec, Double facPagVal, Double facPagRet) {
       this.id = id;
       this.facPagFec = facPagFec;
       this.facPagVal = facPagVal;
       this.facPagRet = facPagRet;
    }
   
    public FacturapagoId getId() {
        return this.id;
    }
    
    public void setId(FacturapagoId id) {
        this.id = id;
    }
    public Date getFacPagFec() {
        return this.facPagFec;
    }
    
    public void setFacPagFec(Date facPagFec) {
        this.facPagFec = facPagFec;
    }
    public Double getFacPagVal() {
        return this.facPagVal;
    }
    
    public void setFacPagVal(Double facPagVal) {
        this.facPagVal = facPagVal;
    }
    public Double getFacPagRet() {
        return this.facPagRet;
    }
    
    public void setFacPagRet(Double facPagRet) {
        this.facPagRet = facPagRet;
    }




}


