package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * FacturaId generated by hbm2java
 */
public class FacturaId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2861395363672113750L;
	private Long conNro;
     private Long empCod;
     private Long facNro;

    public FacturaId() {
    }

    public FacturaId(Long conNro, Long empCod, Long facNro) {
       this.conNro = conNro;
       this.empCod = empCod;
       this.facNro = facNro;
    }
   
    public Long getConNro() {
        return this.conNro;
    }
    
    public void setConNro(Long conNro) {
        this.conNro = conNro;
    }
    public Long getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Long empCod) {
        this.empCod = empCod;
    }
    public Long getFacNro() {
        return this.facNro;
    }
    
    public void setFacNro(Long facNro) {
        this.facNro = facNro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaId) ) return false;
		 FacturaId castOther = ( FacturaId ) other; 
         
		 return ( (this.getConNro()==castOther.getConNro()) || ( this.getConNro()!=null && castOther.getConNro()!=null && this.getConNro().equals(castOther.getConNro()) ) )
 && ( (this.getEmpCod()==castOther.getEmpCod()) || ( this.getEmpCod()!=null && castOther.getEmpCod()!=null && this.getEmpCod().equals(castOther.getEmpCod()) ) )
 && ( (this.getFacNro()==castOther.getFacNro()) || ( this.getFacNro()!=null && castOther.getFacNro()!=null && this.getFacNro().equals(castOther.getFacNro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getConNro() == null ? 0 : this.getConNro().hashCode() );
         result = 37 * result + ( getEmpCod() == null ? 0 : this.getEmpCod().hashCode() );
         result = 37 * result + ( getFacNro() == null ? 0 : this.getFacNro().hashCode() );
         return result;
   }   


}


