package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7194975817620723670L;
	private FacturaId id;
     private Date facFech;
     private Double facVal;

    public Factura() {
    }

    public Factura(FacturaId id, Date facFech, Double facVal) {
       this.id = id;
       this.facFech = facFech;
       this.facVal = facVal;
    }
   
    public FacturaId getId() {
        return this.id;
    }
    
    public void setId(FacturaId id) {
        this.id = id;
    }
    public Date getFacFech() {
        return this.facFech;
    }
    
    public void setFacFech(Date facFech) {
        this.facFech = facFech;
    }
    public Double getFacVal() {
        return this.facVal;
    }
    
    public void setFacVal(Double facVal) {
        this.facVal = facVal;
    }




}


