package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * FacturapagoId generated by hbm2java
 */
public class FacturapagoId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6922399889449355578L;
	private Long conNro;
     private Long empCod;
     private Long facNro;
     private Long facPagNro;

    public FacturapagoId() {
    }

    public FacturapagoId(Long conNro, Long empCod, Long facNro, Long facPagNro) {
       this.conNro = conNro;
       this.empCod = empCod;
       this.facNro = facNro;
       this.facPagNro = facPagNro;
    }
   
    public Long getConNro() {
        return this.conNro;
    }
    
    public void setConNro(Long conNro) {
        this.conNro = conNro;
    }
    public Long getEmpCod() {
        return this.empCod;
    }
    
    public void setEmpCod(Long empCod) {
        this.empCod = empCod;
    }
    public Long getFacNro() {
        return this.facNro;
    }
    
    public void setFacNro(Long facNro) {
        this.facNro = facNro;
    }
    public Long getFacPagNro() {
        return this.facPagNro;
    }
    
    public void setFacPagNro(Long facPagNro) {
        this.facPagNro = facPagNro;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturapagoId) ) return false;
		 FacturapagoId castOther = ( FacturapagoId ) other; 
         
		 return ( (this.getConNro()==castOther.getConNro()) || ( this.getConNro()!=null && castOther.getConNro()!=null && this.getConNro().equals(castOther.getConNro()) ) )
 && ( (this.getEmpCod()==castOther.getEmpCod()) || ( this.getEmpCod()!=null && castOther.getEmpCod()!=null && this.getEmpCod().equals(castOther.getEmpCod()) ) )
 && ( (this.getFacNro()==castOther.getFacNro()) || ( this.getFacNro()!=null && castOther.getFacNro()!=null && this.getFacNro().equals(castOther.getFacNro()) ) )
 && ( (this.getFacPagNro()==castOther.getFacPagNro()) || ( this.getFacPagNro()!=null && castOther.getFacPagNro()!=null && this.getFacPagNro().equals(castOther.getFacPagNro()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getConNro() == null ? 0 : this.getConNro().hashCode() );
         result = 37 * result + ( getEmpCod() == null ? 0 : this.getEmpCod().hashCode() );
         result = 37 * result + ( getFacNro() == null ? 0 : this.getFacNro().hashCode() );
         result = 37 * result + ( getFacPagNro() == null ? 0 : this.getFacPagNro().hashCode() );
         return result;
   }   


}


