package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Geominas generated by hbm2java
 */
public class Geominas  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2487865912046968568L;
	private String geoCod;
     private String geoDes;

    public Geominas() {
    }

    public Geominas(String geoCod, String geoDes) {
       this.geoCod = geoCod;
       this.geoDes = geoDes;
    }
   
    public String getGeoCod() {
        return this.geoCod;
    }
    
    public void setGeoCod(String geoCod) {
        this.geoCod = geoCod;
    }
    public String getGeoDes() {
        return this.geoDes;
    }
    
    public void setGeoDes(String geoDes) {
        this.geoDes = geoDes;
    }




}


