package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Grupdet generated by hbm2java
 */
public class Grupdet  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5520014285123786451L;
	private GrupdetId id;

    public Grupdet() {
    }

    public Grupdet(GrupdetId id) {
       this.id = id;
    }
   
    public GrupdetId getId() {
        return this.id;
    }
    
    public void setId(GrupdetId id) {
        this.id = id;
    }




}


