package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * GrupdetId generated by hbm2java
 */
public class GrupdetId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -59145935510528078L;
	private String grupCodigo;
     private String usuaCodigo;

    public GrupdetId() {
    }

    public GrupdetId(String grupCodigo, String usuaCodigo) {
       this.grupCodigo = grupCodigo;
       this.usuaCodigo = usuaCodigo;
    }
   
    public String getGrupCodigo() {
        return this.grupCodigo;
    }
    
    public void setGrupCodigo(String grupCodigo) {
        this.grupCodigo = grupCodigo;
    }
    public String getUsuaCodigo() {
        return this.usuaCodigo;
    }
    
    public void setUsuaCodigo(String usuaCodigo) {
        this.usuaCodigo = usuaCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GrupdetId) ) return false;
		 GrupdetId castOther = ( GrupdetId ) other; 
         
		 return ( (this.getGrupCodigo()==castOther.getGrupCodigo()) || ( this.getGrupCodigo()!=null && castOther.getGrupCodigo()!=null && this.getGrupCodigo().equals(castOther.getGrupCodigo()) ) )
 && ( (this.getUsuaCodigo()==castOther.getUsuaCodigo()) || ( this.getUsuaCodigo()!=null && castOther.getUsuaCodigo()!=null && this.getUsuaCodigo().equals(castOther.getUsuaCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrupCodigo() == null ? 0 : this.getGrupCodigo().hashCode() );
         result = 37 * result + ( getUsuaCodigo() == null ? 0 : this.getUsuaCodigo().hashCode() );
         return result;
   }   


}


