package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Numer generated by hbm2java
 */
public class Numer  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2519007535497037116L;
	private Long numCod;
     private Long numUlt;
     private String numDes;

    public Numer() {
    }

    public Numer(Long numCod, Long numUlt, String numDes) {
       this.numCod = numCod;
       this.numUlt = numUlt;
       this.numDes = numDes;
    }
   
    public Long getNumCod() {
        return this.numCod;
    }
    
    public void setNumCod(Long numCod) {
        this.numCod = numCod;
    }
    public Long getNumUlt() {
        return this.numUlt;
    }
    
    public void setNumUlt(Long numUlt) {
        this.numUlt = numUlt;
    }
    public String getNumDes() {
        return this.numDes;
    }
    
    public void setNumDes(String numDes) {
        this.numDes = numDes;
    }




}


