package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Observa generated by hbm2java
 */
public class Observa  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8980873069838839808L;
	private String obsCod;
     private String obsDes;

    public Observa() {
    }

	
    public Observa(String obsCod) {
        this.obsCod = obsCod;
    }
    public Observa(String obsCod, String obsDes) {
       this.obsCod = obsCod;
       this.obsDes = obsDes;
    }
   
    public String getObsCod() {
        return this.obsCod;
    }
    
    public void setObsCod(String obsCod) {
        this.obsCod = obsCod;
    }
    public String getObsDes() {
        return this.obsDes;
    }
    
    public void setObsDes(String obsDes) {
        this.obsDes = obsDes;
    }




}


