package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8763716093110899538L;
	private PermisosId id;

    public Permisos() {
    }

    public Permisos(PermisosId id) {
       this.id = id;
    }
   
    public PermisosId getId() {
        return this.id;
    }
    
    public void setId(PermisosId id) {
        this.id = id;
    }




}


