package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * PermisosId generated by hbm2java
 */
public class PermisosId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6975743404832700533L;
	private String grupCodigo;
     private String progCodigo;
     private String evenCodigo;

    public PermisosId() {
    }

    public PermisosId(String grupCodigo, String progCodigo, String evenCodigo) {
       this.grupCodigo = grupCodigo;
       this.progCodigo = progCodigo;
       this.evenCodigo = evenCodigo;
    }
   
    public String getGrupCodigo() {
        return this.grupCodigo;
    }
    
    public void setGrupCodigo(String grupCodigo) {
        this.grupCodigo = grupCodigo;
    }
    public String getProgCodigo() {
        return this.progCodigo;
    }
    
    public void setProgCodigo(String progCodigo) {
        this.progCodigo = progCodigo;
    }
    public String getEvenCodigo() {
        return this.evenCodigo;
    }
    
    public void setEvenCodigo(String evenCodigo) {
        this.evenCodigo = evenCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosId) ) return false;
		 PermisosId castOther = ( PermisosId ) other; 
         
		 return ( (this.getGrupCodigo()==castOther.getGrupCodigo()) || ( this.getGrupCodigo()!=null && castOther.getGrupCodigo()!=null && this.getGrupCodigo().equals(castOther.getGrupCodigo()) ) )
 && ( (this.getProgCodigo()==castOther.getProgCodigo()) || ( this.getProgCodigo()!=null && castOther.getProgCodigo()!=null && this.getProgCodigo().equals(castOther.getProgCodigo()) ) )
 && ( (this.getEvenCodigo()==castOther.getEvenCodigo()) || ( this.getEvenCodigo()!=null && castOther.getEvenCodigo()!=null && this.getEvenCodigo().equals(castOther.getEvenCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGrupCodigo() == null ? 0 : this.getGrupCodigo().hashCode() );
         result = 37 * result + ( getProgCodigo() == null ? 0 : this.getProgCodigo().hashCode() );
         result = 37 * result + ( getEvenCodigo() == null ? 0 : this.getEvenCodigo().hashCode() );
         return result;
   }   


}


