package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Programa1 generated by hbm2java
 */
public class Programa1  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8931417399448443451L;
	private Programa1Id id;
     private String evenDescri;

    public Programa1() {
    }

    public Programa1(Programa1Id id, String evenDescri) {
       this.id = id;
       this.evenDescri = evenDescri;
    }
   
    public Programa1Id getId() {
        return this.id;
    }
    
    public void setId(Programa1Id id) {
        this.id = id;
    }
    public String getEvenDescri() {
        return this.evenDescri;
    }
    
    public void setEvenDescri(String evenDescri) {
        this.evenDescri = evenDescri;
    }




}


