package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Radiacion generated by hbm2java
 */
public class Radiacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7007716874264171921L;
	private String radCod;
     private String radDes;

    public Radiacion() {
    }

    public Radiacion(String radCod, String radDes) {
       this.radCod = radCod;
       this.radDes = radDes;
    }
   
    public String getRadCod() {
        return this.radCod;
    }
    
    public void setRadCod(String radCod) {
        this.radCod = radCod;
    }
    public String getRadDes() {
        return this.radDes;
    }
    
    public void setRadDes(String radDes) {
        this.radDes = radDes;
    }




}


