package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Revelado generated by hbm2java
 */
public class Revelado  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5912098115049334524L;
	private Long revNro;
     private Date revFec;
     private String revDes;

    public Revelado() {
    }

	
    public Revelado(Long revNro) {
        this.revNro = revNro;
    }
    public Revelado(Long revNro, Date revFec, String revDes) {
       this.revNro = revNro;
       this.revFec = revFec;
       this.revDes = revDes;
    }
   
    public Long getRevNro() {
        return this.revNro;
    }
    
    public void setRevNro(Long revNro) {
        this.revNro = revNro;
    }
    public Date getRevFec() {
        return this.revFec;
    }
    
    public void setRevFec(Date revFec) {
        this.revFec = revFec;
    }
    public String getRevDes() {
        return this.revDes;
    }
    
    public void setRevDes(String revDes) {
        this.revDes = revDes;
    }




}


