package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2069707371583043327L;
	private String socCod;
     private String socDes;
     private Long socNit;
     private String socNom;
     private String socApe1;
     private String socApe2;
     private String socDir;
     private String socTel;
     private String socFax;
     private String socMail;

    public Socios() {
    }

    public Socios(String socCod, String socDes, Long socNit, String socNom, String socApe1, String socApe2, String socDir, String socTel, String socFax, String socMail) {
       this.socCod = socCod;
       this.socDes = socDes;
       this.socNit = socNit;
       this.socNom = socNom;
       this.socApe1 = socApe1;
       this.socApe2 = socApe2;
       this.socDir = socDir;
       this.socTel = socTel;
       this.socFax = socFax;
       this.socMail = socMail;
    }
   
    public String getSocCod() {
        return this.socCod;
    }
    
    public void setSocCod(String socCod) {
        this.socCod = socCod;
    }
    public String getSocDes() {
        return this.socDes;
    }
    
    public void setSocDes(String socDes) {
        this.socDes = socDes;
    }
    public Long getSocNit() {
        return this.socNit;
    }
    
    public void setSocNit(Long socNit) {
        this.socNit = socNit;
    }
    public String getSocNom() {
        return this.socNom;
    }
    
    public void setSocNom(String socNom) {
        this.socNom = socNom;
    }
    public String getSocApe1() {
        return this.socApe1;
    }
    
    public void setSocApe1(String socApe1) {
        this.socApe1 = socApe1;
    }
    public String getSocApe2() {
        return this.socApe2;
    }
    
    public void setSocApe2(String socApe2) {
        this.socApe2 = socApe2;
    }
    public String getSocDir() {
        return this.socDir;
    }
    
    public void setSocDir(String socDir) {
        this.socDir = socDir;
    }
    public String getSocTel() {
        return this.socTel;
    }
    
    public void setSocTel(String socTel) {
        this.socTel = socTel;
    }
    public String getSocFax() {
        return this.socFax;
    }
    
    public void setSocFax(String socFax) {
        this.socFax = socFax;
    }
    public String getSocMail() {
        return this.socMail;
    }
    
    public void setSocMail(String socMail) {
        this.socMail = socMail;
    }




}


