package com.agileillutions.gesdos.modelo;
// Generated Nov 5, 2016 11:06:58 PM by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Traba generated by hbm2java
 */
public class Traba  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1859508765942790679L;
	private Long traCed;
     private String traNom;
     private String traApe1;
     private String traApe2;
     private Date traFecIni;
     private String traEst;
     private String traObs;
     private String traSex;

    public Traba() {
    }

	
    public Traba(Long traCed, String traNom, String traApe1, String traApe2, Date traFecIni, String traEst, String traSex) {
        this.traCed = traCed;
        this.traNom = traNom;
        this.traApe1 = traApe1;
        this.traApe2 = traApe2;
        this.traFecIni = traFecIni;
        this.traEst = traEst;
        this.traSex = traSex;
    }
    public Traba(Long traCed, String traNom, String traApe1, String traApe2, Date traFecIni, String traEst, String traObs, String traSex) {
       this.traCed = traCed;
       this.traNom = traNom;
       this.traApe1 = traApe1;
       this.traApe2 = traApe2;
       this.traFecIni = traFecIni;
       this.traEst = traEst;
       this.traObs = traObs;
       this.traSex = traSex;
    }
   
    public Long getTraCed() {
        return this.traCed;
    }
    
    public void setTraCed(Long traCed) {
        this.traCed = traCed;
    }
    public String getTraNom() {
        return this.traNom;
    }
    
    public void setTraNom(String traNom) {
        this.traNom = traNom;
    }
    public String getTraApe1() {
        return this.traApe1;
    }
    
    public void setTraApe1(String traApe1) {
        this.traApe1 = traApe1;
    }
    public String getTraApe2() {
        return this.traApe2;
    }
    
    public void setTraApe2(String traApe2) {
        this.traApe2 = traApe2;
    }
    public Date getTraFecIni() {
        return this.traFecIni;
    }
    
    public void setTraFecIni(Date traFecIni) {
        this.traFecIni = traFecIni;
    }
    public String getTraEst() {
        return this.traEst;
    }
    
    public void setTraEst(String traEst) {
        this.traEst = traEst;
    }
    public String getTraObs() {
        return this.traObs;
    }
    
    public void setTraObs(String traObs) {
        this.traObs = traObs;
    }
    public String getTraSex() {
        return this.traSex;
    }
    
    public void setTraSex(String traSex) {
        this.traSex = traSex;
    }




}


